id: I84894A5F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:03:04+00:00'
last_modified: '2022-06-09T05:38:45.386975+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25707
  title: ཀྲུང་གོའི་གུང་ཁྲན་ཏང་གི་འགན་འདེད་སྲོལ་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CBD4:
      image_group_id: I1KG25709
      title: Volume 1 of krung go'i gung khran tang gi 'gan 'ded srol yig
      total_pages: 19
      order: 1
      base_file: CBD4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
