id: P007118
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25707
  title: ཀྲུང་གོའི་གུང་ཁྲན་ཏང་གི་འགན་འདེད་སྲོལ་ཡིག
  author: ''
  volumes:
    81a1cd48016e4264b3edfcecf8e40461:
      image_group_id: I1KG25709
      title: ''
      volume_number: 1
      total_pages: 19
ebook_metadata:
  title: ཀྲུང་གོའི་གུང་ཁྲན་ཏང་གི་འགན་འདེད་སྲོལ་ཡིག
  author: ''
  sku: P007118
  cover: cover.jpg
  layers:
  - pagination
