id: P007118
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25707
  title: ཀྲུང་གོའི་གུང་ཁྲན་ཏང་གི་འགན་འདེད་སྲོལ་ཡིག
  author: ''
  volumes:
    bfece91f85224ff38d9147d75500f65b:
      image_group_id: I1KG25709
      title: Volume 1 of krung go'i gung khran tang gi 'gan 'ded srol yig
      volume_number: 1
      total_pages: 19
      base_file: v001.txt
ebook_metadata:
  title: ཀྲུང་གོའི་གུང་ཁྲན་ཏང་གི་འགན་འདེད་སྲོལ་ཡིག
  author: ''
  sku: P007118
  cover: cover.jpg
  layers:
  - pagination
